# Generated by Django 6.0.4 on 2026-05-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pc_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kompyuter nomi"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Oxirgi faollik"),
                ),
            ],
            options={
                "verbose_name": "Kompyuter",
                "verbose_name_plural": "Kompyuterlar",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="USBDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pnp_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="PNP ID"
                    ),
                ),
                (
                    "caption",
                    models.CharField(max_length=255, verbose_name="Qurilma nomi"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("allowed", "Ruxsat berilgan"),
                            ("blocked", "Bloklangan"),
                            ("pending", "Kutilmoqda"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Birinchi ulangan"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Oxirgi ulangan"),
                ),
                (
                    "pc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.clientpc",
                        verbose_name="Kompyuter",
                    ),
                ),
            ],
            options={
                "verbose_name": "USB Qurilma",
                "verbose_name_plural": "USB Qurilmalar",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="USBLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usb_caption",
                    models.CharField(max_length=255, verbose_name="Qurilma nomi"),
                ),
                ("pnp_id", models.CharField(max_length=255, verbose_name="PNP ID")),
                ("action", models.CharField(max_length=100, verbose_name="Harakat")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vaqt"),
                ),
                (
                    "pc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.clientpc",
                        verbose_name="Kompyuter",
                    ),
                ),
            ],
            options={
                "verbose_name": "USB Log",
                "verbose_name_plural": "USB Loglar",
                "ordering": ["-timestamp"],
            },
        ),
    ]
